### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by divyanshusood**
The data will help to develop BER map of Ireland that will provide access to building energy information on dwelling clusters within Ireland. The map showcase the benefits of using geo-located BER data.

### CODE REVIEW

**Comment by rdmolony** [comment]
Hi @divyanshusood, thanks for contributing!  Would you please be able to upload your data to [Zenodo](https://zenodo.org) and then link the README to this URL?

Zenodo is better suited than Github to store raw data as it allows more customisation for:
- Links to academic papers
- Date of data upload
- GitHub limits storage so not well suited for large data files
- etc

I've changed the [Contributing Guidelines](https://github.com/energy-modelling-ireland/energy-data-sources/blob/master/CONTRIBUTING.md) & README to reflect this.

Is it possible to access this data [from source](https://renewables.maps.arcgis.com/apps/webappviewer/index.html?id=360f7b3f6f484d7d89b967b41231daef) instead or is this raw data file you've uploaded the only way to access this information?  Thanks again :)

**Comment by divyanshusood** [comment]
Hi Rowan,

The is available on SEAI website and can be found on these links:
https://www.seai.ie/technologies/seai-maps/ber-map/ <https://www.seai.ie/technologies/seai-maps/ber-map/> 
https://www.seai.ie/technologies/seai-maps/ber-map/BER_data.csv <https://www.seai.ie/technologies/seai-maps/ber-map/BER_data.csv>
https://www.seai.ie/technologies/seai-maps/ber-map/Description-of-variables-for-BER-map.xlsx <https://www.seai.ie/technologies/seai-maps/ber-map/Description-of-variables-for-BER-map.xlsx>

I will upload it to Zenodo and then link it. 

Thank you
Divyanshu Sood

**Comment by rdmolony** [comment]
Hi @divyanshusood, no need to upload it to Zenodo if there is a URL link to source!  Why not add something like:

- Name of source:  SEAI BER Map
- Short description:  ...
- Data: https://www.seai.ie/technologies/seai-maps/ber-map/BER_data.csv
- Glossary: https://www.seai.ie/technologies/seai-maps/ber-map/Description-of-variables-for-BER-map.xlsx

That way the data source will remain 'Live' and the URL is to source rather than to a copy.

Zenodo is more useful for data that isn't available online

**Comment by rdmolony** [comment]
Also as I've added a few commits to the master Github repository your pull request is now behind master and so you won't be able to merge it until you either merge it your branch `divyanshusood-patch-1` with the `master` branch or rebase on top of `master`.  If you're not familiar with `git` the easiest thing to do is to (1) close this pull request, (2) start again editing the `master` README and (3) submit a new pull request

**Pull request closed without merging**
